### ISSUE TITLE
No feedback on construct query errors

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/PySPARQL-Anything#26]
There are cases where the query is malformed but there is no error reporting.

Example:

```python

result = engine.construct(query="constru ct * where { service <x-sparql-anything:> { ?s ?p ?o } }")
print(result)
```
Shows an empty rdflib graph.

**Comment by enridaga** [comment]
Probably the solution to #27 would also solve this issue.

**Comment by MarcoR1791** [comment]
Malformed queries now raise a ```SPARQLAnythingException``` with version ```v1.0.0.0```. See the example below:
```
>>> engine.construct(query="constru ct * where { service <x-sparql-anything:> { ?s ?p ?o } }")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mr24397\AppData\Local\Programs\Python\Python311\Lib\site-packages\pysparql_anything\sparql_anything.py", line 124, in construct
    return self.executor.execute_construct(kwargs, graph_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mr24397\AppData\Local\Programs\Python\Python311\Lib\site-packages\pysparql_anything\executor.py", line 98, in execute_construct
    raise SPARQLAnythingException(err_msg)
pysparql_anything.executor.SPARQLAnythingException: SPARQL syntax error (or query file does not exists): Lexical error at line 1, column 8.  Encountered: '32' (32), after prefix "constru"
>>>
```
