### ISSUE TITLE
Inconsistent error on malformed select

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/PySPARQL-Anything#27]
Sometimes the query is syntactically wrong but the system reports a json decoding error. We should find a way of capturing the Java error somehow and provide a meaningful feedback to users.

Example:

```python

result = engine.select(query="select sometimes * where { service <x-sparql-anything:> { ?s ?p ?o } }")
print(result)
```

**Comment by enridaga** [comment]
The first thing to try would be wrap this line in a try/except block and see if any exception is raised when passing a query with a syntax error.

https://github.com/SPARQL-Anything/PySPARQL-Anything/blob/f1edb42666836335a1c74d26b3ff6045188398ce/src/pysparql_anything/sparql_anything_reflection.py#L82

**Comment by MarcoR1791** [comment]
So I have reproduced this. The main problem is that ```self.reflection.callMain(args) ``` returns an empty string for a syntactically wrong query. 

Could the problem be in the java ```callMain``` method?

**Comment by MarcoR1791** [comment]
Actually, when the same query is executed with the CLI, one obtains
```
C:\Users\mr24397\Work Folders\Desktop>sparql-anything -q test_query_1.sparql
[main] WARN io.github.sparqlanything.cli.SPARQLAnything - jena-geosparql dependency not available
[main] ERROR io.github.sparqlanything.cli.SPARQLAnything - SPARQL syntax error (or query file does not exists): Lexical error at line 1, column 17.  Encountered: '32' (32), after prefix "sometimes"
```

I think this might be down to the function ```callMain``` in ```SPARQLAnything.java``` only capturing STDOUT and not STDERR which prints the exceptions?

**Comment by enridaga** [comment]
Yes, if an exception is raised, that string content is not sent to STDIN (the returned output) but to STDERR. Can we capture the Java process STDERR from the python code? 

One could change Java.callMain to return STDERR in case of errors, but the problem with this second solution is that Python won't know if an error occurred...

**Comment by MarcoR1791** [comment]
Hmm. I may need help here.

So it seems that using the system methods of Python I can only capture the output streams when they come from the Python interpreter.

What I decided to do then is to use ```pyjnius``` to reproduce the ```callMain``` function in Python hoping that doing this would give me access to the Java streams. Now, funnily enough, when I set it to capture STDOUT it works just like it does in the original Java method! 
But when I try to capture STDERR all I get back is an empty string....

This is the code that I wrote to mimick the Java ```callMain``` method:
```python
def call_main(self, args: list[str]) -> str:
        """
        Wrapper for the public static String callMain(String args) method of
        SPARQLAnything.\n
        Args:\n
            args: A Python list[str] that mirrors the String[] args that
                is required by callMain(String[] args).\n
        Returns:\n
            A string containing the query output.
        """
        baos = self.BAOS()
        ps = self.PrintStream(baos, False)
        old_ps = self.System.out
        self.System.setOut(ps)
        self.reflection.main(args)
        # Put things back
        self.System.out.flush()
        self.System.setOut(old_ps)
        sa_output = baos.toString()
        print("Output:", sa_output)
        return sa_output
```
To capture STDERR I just change 'out' to 'err'.

**Comment by enridaga** [comment]
> Hmm. I may need help here.
> 
> So it seems that using the system methods of Python I can only capture the output streams when they come from the Python interpreter.
> 
> What I decided to do then is to use `pyjnius` to reproduce the `callMain` function in Python hoping that doing this would give me access to the Java streams. Now, funnily enough, when I set it to capture STDOUT it works just like it does in the original Java method! But when I try to capture STDERR all I get back is an empty string....

I see, because the exception is not captured. Can you wrap everything in a try/except block? Would that catch the Java Exception?

**Comment by MarcoR1791** [comment]
OK! So I have managed to make it work I think. I capture both the STDOUT and the STDERR from the Python code and have wrapped both in a ```SPARQLAnythingQueryOuput``` dataclass (with two string attributes, ```err``` and ```out```). 

This is then passed on to the remaining methods to postprocess. The first part of this postprocessing is now parsing the STDERR message for the ```ERROR``` keyword. If this is found then a new ```SPARQLAnythingException``` is raised with the corresponding message before the rest of the code can be executed.

For the example of the first comment we then have
```
>>> e.select(query="select sometimes * where { service <x-sparql-anything:> { ?s ?p ?o } }")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mr24397\AppData\Local\Programs\Python\Python311\Lib\site-packages\pysparql_anything\sparql_anything.py", line 80, in select
    return cmd.execute_select(kwargs, self.receiver, output_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mr24397\AppData\Local\Programs\Python\Python311\Lib\site-packages\pysparql_anything\command.py", line 130, in execute_select
    raise SPARQLAnythingException(err_msg)
pysparql_anything.command.SPARQLAnythingException: SPARQL syntax error (or query file does not exists): Lexical error at line 1, column 17.  Encountered: '32' (32), after prefix "sometimes"
>>>
```

**Comment by enridaga** [comment]
Fantastic! That's all we wanted :)
