### ISSUE TITLE
Uninformative error message when query not found

### ISSUE THREAD

**Issue by jmmcd** [SPARQL-Anything/PySPARQL-Anything#9]
Version: `sparql-anything-v0.8.2.jar`

This issue is not an important one. It could be a small cosmetic improvement.

When I tried to `sa.run()` a query as below, it failed because I mistyped the filename, with the error as below. I think the error message could be more informative, eg `FileNotFoundError`.

```
In [4]: sa.run(q='query1.sparql')
[main] INFO com.github.sparqlanything.cli.SPARQLAnything - SPARQL anything
---------------------------------------------------------------------------
JavaException                             Traceback (most recent call last)
Cell In[4], line 1
----> 1 sa.run(q='query1.sparql')

File ~\miniconda3\Lib\site-packages\pysparql_anything\sparql_anything.py:30, in SparqlAnything.run(self, **kwargs)
     23 """
     24 The run method replaces the regular command line execution.
     25 @param **kwargs The keyword arguments are the same as the regular
     26     flags for the Sparql Anything CLI, minus the hyphen.
     27 See the User Guide for an example.
     28 """
     29 command = cmd.RunCommand(kwargs, self.receiver)
---> 30 command.execute()

File ~\miniconda3\Lib\site-packages\pysparql_anything\command.py:159, in RunCommand.execute(self)
    157 """ instructions for a run request """
    158 args = super()._combine()
--> 159 self.receiver.main(args)

File ~\miniconda3\Lib\site-packages\pysparql_anything\engine.py:39, in Engine.main(self, args)
     37 def main(self, args):
     38     """ Wrapper for the SPARQL Anything main method. """
---> 39     self.reflection.main(args)

File jnius\\jnius_export_class.pxi:876, in jnius.JavaMethod.__call__()

File jnius\\jnius_export_class.pxi:1059, in jnius.JavaMethod.call_staticmethod()

File jnius\\jnius_utils.pxi:79, in jnius.check_exception()

JavaException: JVM exception occurred: Lexical error at line 1, column 14.  Encountered: <EOF> after prefix "query1.sparql" org.apache.jena.query.QueryParseException
```

**Comment by MarcoR1791** [comment]
Hi James,

I could implement a preliminary check on whether the file exists that returns a FileNotFoundError.

The JavaException however comes from SPARQL Anything and is simply thrown onto the terminal by PySPARQL. 

@enridaga Thoughts? Should I go ahead and implement what I suggested above?

**Comment by MarcoR1791** [comment]
This has been fixed in the upcoming v1.0.0.0 of PySPARQL-Anything.
Examples below:
1. The ```run``` command now prints the logger output from SPARQL-Anything. NOTE: ```run``` now also works in notebooks and not just in the command prompt shell.
```
>>> engine.run(q="foobar.sparql")
[main] WARN io.github.sparqlanything.cli.SPARQLAnything - jena-geosparql dependency not available
[main] ERROR io.github.sparqlanything.cli.SPARQLAnything - SPARQL syntax error (or query file does not exists): Lexical error at line 1, column 14.  Encountered: <EOF> after prefix "foobar.sparql"
```
2. The other commands raise a ```SPARQLAnythingException``` 
```
>>> engine.select(q="foobar.sparql")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mr24397\AppData\Local\Programs\Python\Python311\Lib\site-packages\pysparql_anything\sparql_anything.py", line 81, in select
    return self.executor.execute_select(kwargs, output_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mr24397\AppData\Local\Programs\Python\Python311\Lib\site-packages\pysparql_anything\executor.py", line 129, in execute_select
    raise SPARQLAnythingException(err_msg)
pysparql_anything.executor.SPARQLAnythingException: SPARQL syntax error (or query file does not exists): Lexical error at line 1, column 14.  Encountered: <EOF> after prefix "foobar.sparql"
```
